platform:ios, ’8.0’

target ‘myMakeMoneyStudy’ do
	pod 'AsyncDisplayKit', '~> 1.9.80'
	pod 'AFNetworking', '~> 3.1.0'
	pod 'Masonry', '~> 1.0.1'
	pod 'SDWebImage', '~> 3.8.1'
	pod 'SVWebViewController', '~> 1.0'
	pod 'NJKWebViewProgress', '~> 0.2.3'
end

